media_folder: 'static/uploads'
public_folder: '/uploads'


collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: 'Title', name: 'title', widget: 'string'}
      - {label: 'Cover', name: 'featureimg', widget: 'image'}
      - {label: 'Body', name: 'body', widget: 'markdown'}